site_name: zhizhi·lovethislife
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: blue
    accent: light blue

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 主页: index.md
  - 笔记:
    - 笔记首页: course/index.md
    - 心理学研究技术:
      - 眼动基础: course/psychtech/眼动基础/index.md
      - fMRI: course/psychtech/fMRI/index.md
      - 无创神经调控: course/psychtech/无创神经调控/index.md
  - 生活:
    - 生活首页: life/index.md
    - 舞蹈: life/dance/index.md
    - 歌单: life/playlist/index.md
    - 书单: life/books/index.md
  - 友链: friends/index.md
  - 关于: about/index.md
