site_name: zhizhi·lovethislife
theme:
  name: material
  language: zh

nav:
  - 主页: index.md
  - 笔记:
    - 笔记首页: course/index.md
    - 示例文档: course/example.md
  - 生活: life/index.md
  - 友链: friends/index.md
